tasks_cfgs:
  nut_assembly:
    name: nut_assembly
    n_tasks: 9
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    loss_mul: 1
    task_per_batch: 9
    traj_per_subtask: 100
    demo_per_subtask: 100
  door:
    name: door
    n_tasks: 4
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 8
    task_ids:
    - 0
    - 1
    - 2
    - 3
    loss_mul: 1
    task_per_batch: 4
    traj_per_subtask: 100
    demo_per_subtask: 100
  drawer:
    name: drawer
    n_tasks: 8
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    loss_mul: 1
    task_per_batch: 8
    traj_per_subtask: 100
    demo_per_subtask: 100
  button:
    name: button
    n_tasks: 6
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 5
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    loss_mul: 1
    task_per_batch: 6
    traj_per_subtask: 100
    demo_per_subtask: 100
  pick_place:
    name: pick_place
    n_tasks: 16
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 8
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    loss_mul: 1
    task_per_batch: 16
    traj_per_subtask: 100
    demo_per_subtask: 100
  stack_block:
    name: stack_block
    n_tasks: 6
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 5
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    loss_mul: 1
    task_per_batch: 6
    traj_per_subtask: 100
    demo_per_subtask: 100
  basketball:
    name: basketball
    n_tasks: 12
    crop:
    - 0
    - 0
    - 0
    - 0
    n_per_task: 3
    task_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    loss_mul: 1
    task_per_batch: 12
    traj_per_subtask: 100
    demo_per_subtask: 100
debug: false
EXPERT_DATA: /home/frosa_loc/multitask_dataset_ur/multitask_dataset_language_command
save_path: /media/ciccio/Sandisk/mosaic-baseline-sav-folder/mosaic-baseline-sav-folder/ur-baseline
wandb_log: true
project_name: ur_mosaic_baseline_no_obj_detector
log_freq: 1
save_optim: true
resume: false
resume_path: None
resume_step: -1
device: 0
exp_name: 1Task-Pick-Place-Mosaic-No-Obj-Detector-Ur5e-Batch128
epochs: 250
bsize: 128
vsize: 128
optimizer: AdamW
task_names: pick_place
inv_mul: 1
bc_mul: 1
pnt_mul: 0.1
rep_muls:
  img_byol: ${byol.mul_pre}
  attn_byol: ${byol.mul_pos}
  demo_byol: ${byol.mul_demo}
  intm_byol: ${byol.mul_intm}
  simclr_pre: ${simclr.mul_pre}
  simclr_post: ${simclr.mul_pos}
  simclr_intm: ${simclr.mul_intm}
train_cfg:
  batch_size: ${bsize}
  val_size: ${vsize}
  lr: 0.0001
  optimizer: ${optimizer}
  epochs: ${epochs}
  log_freq: ${log_freq}
  save_freq: ${save_freq}
  print_freq: ${print_freq}
  inv_loss_mult: ${inv_mul}
  bc_loss_mult: ${bc_mul}
  pnt_loss_mult: ${pnt_mul}
  rep_loss_muls: ${rep_muls}
  dataset: ${dataset_cfg}
  sampler: ${samplers}
  target_update_freq: 5
  early_stopping: ${early_stopping_cfg}
  weight_decay: 0.05
  lr_schedule: None
early_stopping_cfg:
  patience: 20
  delta: 0.001
tasks:
- name: pick_place
  n_tasks: 16
  crop:
  - 0
  - 0
  - 0
  - 0
  n_per_task: 8
  task_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  loss_mul: 1
  task_per_batch: 16
  traj_per_subtask: 100
  demo_per_subtask: 100
single_task: false
exclude_task: false
use_all_tasks: false
set_same_n: -1
limit_num_traj: -1
limit_num_demo: -1
loader_workers: 20
samplers:
  batch_size: ${bsize}
  drop_last: false
  shuffle: true
  balancing_policy: 1
val_skip: false
train_skip: true
dataset_cfg:
  _target_: multi_task_il.datasets.multi_task_datasets.MultiTaskPairedDataset
  root_dir: ${EXPERT_DATA}/
  mode: ???
  tasks_spec: ${tasks}
  aux_pose: true
  height: 100
  width: 180
  split:
  - 0.9
  - 0.1
  demo_T: 4
  obs_T: 7
  normalize_action: true
  normalization_ranges:
  - - -0.35
    - 0.25
  - - -0.3
    - 0.3
  - - 0.6
    - 1.2
  - - -3.14
    - 3.14911766
  - - -3.14911766
    - 3.14911766
  - - -3.14911766
    - 3.14911766
  n_action_bin: 256
  take_first_frame: ${policy.concat_target_obj_embedding}
  data_augs: ${augs}
  non_sequential: false
  crop_twice: false
  state_spec:
  - ee_aa
  - gripper_qpos
  allow_val_skip: ${val_skip}
  allow_train_skip: ${train_skip}
  use_strong_augs: true
  select_random_frames: true
  compute_obj_distribution: true
  agent_name: ur5e
  demo_name: panda
augs:
  strong_jitter: 0.01
  weak_jitter: 0.01
  grayscale: 0.01
  blur:
  - 0.1
  - 2.0
  flip: 0.05
  weak_crop_scale:
  - 0.8
  - 1.0
  strong_crop_scale:
  - 0.6
  - 1.0
  weak_crop_ratio:
  - 1.8
  - 1.8
  strong_crop_ratio:
  - 1.8
  - 1.8
  use_affine: false
  rand_trans: 0.1
simclr:
  demo_T: 4
  obs_T: 7
  mul_pre: 1
  mul_pos: 1
  mul_intm: 0
  tau: 0.005
  compressor_dim: 128
  temporal: true
  hidden_dim: 512
  fix_step: -1
byol:
  p: 2
  project_dim: 128
  hidden_dim: 256
  demo_T: 4
  obs_T: 7
  demo_proj: true
  share_mlp: true
  no_hidden: false
  draw_apart: false
  mul_pre: 0
  mul_pos: 0
  mul_intm: 0
  mul_demo: 0
policy: ${mosaic}
mosaic:
  _target_: multi_task_il.models.mt_rep.VideoImitation
  load_target_obj_detector: false
  target_obj_detector_step: 17204
  target_obj_detector_path: /home/frosa_loc/Multi-Task-LFD-Framework/mosaic-baseline-sav-folder/baseline-1/1Task-Pick-Place-Target-Obj-Random-Frames-Batch128-1gpu-Attn2ly128-Act2ly256mix4-actCat
  freeze_target_obj_detector: false
  remove_class_layers: false
  load_contrastive: true
  concat_target_obj_embedding: false
  latent_dim: 40
  sdim: 8
  concat_state: false
  height: ${train_cfg.dataset.height}
  width: ${train_cfg.dataset.width}
  demo_T: ${train_cfg.dataset.demo_T}
  obs_T: ${train_cfg.dataset.obs_T}
  dim_H: 7
  dim_W: 12
  demo_mean: true
  action_cfg: ${actions}
  concat_demo_head: false
  concat_demo_act: true
  attn_cfg: ${attn}
  byol_config: ${byol}
  simclr_config: ${simclr}
actions:
  n_layers: 2
  out_dim: 256
  hidden_dim: 128
  adim: 7
  n_mixtures: 4
  const_var: false
  sep_var: true
  concat_demo_head: false
  concat_demo_act: true
  demo_mean: true
attn:
  embed_hidden: 256
  dropout: 0.2
  n_attn_layers: 2
  attn_heads: 4
  attn_ff: 128
  pos_enc: true
  fuse_starts: 0
  causal: true
  attend_demo: true
  demo_out: true
  img_cfg:
    network_flag: 0
    out_feature: 256
    drop_dim: 3
    pretrained: true
tosil:
  _target_: multi_task_il.models.baselines.InverseImitation
  latent_dim: 40
  lstm_config:
    out_dim: 32
    n_layers: 1
    is_rnn: false
  vis:
    conv_drop_dim: 3
    st_goal_attn: true
    n_st_attn: 2
    use_pe: true
    attn_heads: 4
  n_mixtures: 4
  const_var: true
  concat_state: false
  pred_point: true
  concat_target_obj_embedding: false
lstm:
  _target_: multi_task_il.models.baselines.InverseImitation
  latent_dim: 40
  lstm_config:
    out_dim: 32
    n_layers: 1
    is_rnn: false
  vis:
    temp_convs: false
    lstm: true
    out_feature: 256
    context_T: 4
  n_mixtures: 2
  const_var: true
  concat_state: false
  pred_point: true
  transformer_feat: false
use_daml: false
daml:
  _target_: multi_task_il.models.baselines.DAMLNetwork
  n_final_convs: resnet
  T_context: 4
  maml_lr: 0.1
  first_order: false
  n_mix: 2
  const_var: true
  inner_iters: 1
